# Verzeichnis "src" als Top-Level-Paket installieren (mit PyCharm ist das nicht notwendig!):
# pip install -e .

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tichu"
version = "0.1.0"

[tool.setuptools]
packages = ["src"]